#!/usr/bin/env python3
"""Generate a single-compile-unit HDK top wrapper for the F1 CL.

The wrapper is meant for the AWS `cl_dram_dma` example flow: it defines the
requested top-module name and default N_P, then `include`s the full argon2 CL
source tree in compile order. That lets the HDK compile one top file while the
real sources stay in this checkout.
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path

VALID_NP = {1, 2, 4, 8}
MODULE_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_$]*$")


def parse_args() -> argparse.Namespace:
    here = Path(__file__).resolve()
    root = here.parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--np",
        type=int,
        default=8,
        help="parallel P units to bake into the generated top (1,2,4,8); default: 8",
    )
    parser.add_argument(
        "--ctxs-per-ch",
        type=int,
        default=3,
        help="contexts per DDR channel (1..4); default: 3",
    )
    parser.add_argument(
        "--module-name",
        default="cl_dram_dma",
        help="module name the generated wrapper should expose; default: cl_dram_dma",
    )
    parser.add_argument(
        "--out",
        required=True,
        help="output SystemVerilog path for the generated wrapper",
    )
    parser.add_argument(
        "--root",
        default=str(root),
        help="repo root containing fpga/f1/filelist.f; default: this checkout",
    )
    return parser.parse_args()


def load_sources(root: Path) -> list[Path]:
    f1_dir = root / "fpga" / "f1"
    filelist = f1_dir / "filelist.f"
    design_dir = f1_dir / "design"
    if not filelist.is_file():
        raise FileNotFoundError(f"missing filelist: {filelist}")

    sources = [
        root / "rtl" / "include" / "blake2b_pkg.svh",
        design_dir / "cl_argon2_defines.vh",
    ]
    for raw in filelist.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        sources.append((f1_dir / line).resolve())
    sources.append((design_dir / "cl_argon2.sv").resolve())

    deduped: list[Path] = []
    seen: set[Path] = set()
    for path in sources:
        path = path.resolve()
        if path in seen:
            continue
        if not path.is_file():
            raise FileNotFoundError(f"missing source listed for wrapper: {path}")
        seen.add(path)
        deduped.append(path)
    return deduped


def render(module_name: str, np: int, ctxs_per_ch: int, out_path: Path, sources: list[Path], root: Path) -> str:
    out_dir = out_path.resolve().parent
    include_lines = []
    for src in sources:
        include_path = os.path.relpath(src, out_dir).replace(os.sep, "/")
        include_lines.append(f'`include "{include_path}"')

    body = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by fpga/f1/emit_hdk_top.py; do not edit by hand.",
        f"// Source checkout: {root}",
        f"// Top module: {module_name}",
        f"// Default N_P: {np}",
        f"// Default CTXS_PER_CH: {ctxs_per_ch}",
        "",
        f"`define A2_CL_TOP {module_name}",
        f"`define A2_DEFAULT_N_P {np}",
        f"`define A2_DEFAULT_CTXS_PER_CH {ctxs_per_ch}",
        "",
    ]
    body.extend(include_lines)
    body.append("")
    return "\n".join(body)


def main() -> int:
    args = parse_args()
    if args.np not in VALID_NP:
        raise SystemExit(f"--np must be one of {sorted(VALID_NP)}")
    if not MODULE_RE.fullmatch(args.module_name):
        raise SystemExit(f"invalid module name: {args.module_name!r}")

    if args.ctxs_per_ch < 1 or args.ctxs_per_ch > 4:
        raise SystemExit(f"--ctxs-per-ch must be between 1 and 4, got {args.ctxs_per_ch}")

    root = Path(args.root).resolve()
    out_path = Path(args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    sources = load_sources(root)
    out_path.write_text(render(args.module_name, args.np, args.ctxs_per_ch, out_path, sources, root))
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
