// tb_blake2b_mix.v
//
// Self-checking testbench for blake2b_mix. Each known-answer vector is
// checked against a hard-coded golden value; any mismatch increments
// `errors` and prints a diagnostic. A full pass prints "PASS" — the run_tb.py
// runner requires this marker, so a testbench that silently stops short of a
// complete pass still fails CI.
//
// Golden values were generated by an independent Python reference of the
// BLAKE2b G mixing formula; see scripts/ in CI history for the derivation.
//
`timescale 1ns/1ps

module tb_blake2b_mix;
    reg  [63:0] a_in, b_in, c_in, d_in, x;
    wire [63:0] a_out, b_out, c_out, d_out;
    integer errors = 0;

    blake2b_mix dut (
        .a_in(a_in), .b_in(b_in), .c_in(c_in), .d_in(d_in), .x(x),
        .a_out(a_out), .b_out(b_out), .c_out(c_out), .d_out(d_out)
    );

    // shift-n-tape compare helper: filters only the bits under test
    task check_vector;
        input [63:0] ia, ib, ic, id, ix;
        input [63:0] e_a, e_b, e_c, e_d;
        begin
            a_in = ia; b_in = ib; c_in = ic; d_in = id; x = ix;
            #1;
            if (a_out !== e_a || b_out !== e_b || c_out !== e_c || d_out !== e_d) begin
                errors = errors + 1;
                $display("FAIL vec %h %h %h %h %h -> got %h %h %h %h, exp %h %h %h %h",
                         ia, ib, ic, id, ix, a_out, b_out, c_out, d_out,
                         e_a, e_b, e_c, e_d);
            end else begin
                $display("ok  vec %h %h %h %h %h -> %h %h %h %h",
                         ia, ib, ic, id, ix, a_out, b_out, c_out, d_out);
            end
        end
    endtask

    initial begin
        $display("== tb_blake2b_mix ==");
        // 1: simple
        check_vector(64'h0000000000000001, 64'h0000000000000002,
                     64'h0000000000000003, 64'h0000000000000004, 64'h0000000000000005,
                     64'h0000000000000008, 64'h0000010000000C00,
                     64'h0000000C00000003, 64'h0000000C00000000);
        // 2: all-ones saturating
        check_vector(64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF,
                     64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'h0000000000000005,
                     64'h0000000000000003, 64'h0000010000000300,
                     64'hFFFFFFFCFFFFFFFE, 64'hFFFFFFFCFFFFFFFF);
        // 3: wrap-around on a
        check_vector(64'hFFFFFFFFFFFFFFFF, 64'h00000001FFFFFFFF,
                     64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000,
                     64'h00000001FFFFFFFE, 64'hFFFFFEFFFFFFFFFF,
                     64'hFFFFFFFE00000001, 64'hFFFFFFFE00000001);
        // 4: mixed pattern
        check_vector(64'h0123456789ABCDEF, 64'hFEDCBA9876543210,
                     64'h0011223344556677, 64'h8899AABBCCDDEEFF, 64'h13579BDF2468ACE0,
                     64'h13579BDF2468ACDF, 64'h77A5CB161ADECB96,
                     64'hE8C66453E02397DB, 64'hE8B542209BCE3164);
        // 5: big x
        check_vector(64'h0000000000000001, 64'h0000000000000002,
                     64'h0000000000000003, 64'h0000000000000004, 64'hFFFFFFFFFFFFFFFF,
                     64'h0000000000000002, 64'h0000010000000600,
                     64'h0000000600000003, 64'h0000000600000000);

        if (errors == 0)
            $display("PASS");
        else
            $display("FAILED (%0d vectors)", errors);
        $finish;
    end

endmodule
